### ISSUE TITLE
Production support and SLA's

### ISSUE THREAD

**Issue by tammyandlee** [netscaler/netscaler-k8s-ingress-controller#629]
We are looking at using the controller in our production environment. Can we purchase support for the product and do you know the SLA's around the support?

Thanks,
Lee

**Comment by bhardwajk** [comment]
Hello Lee, Sure. Can you please send me an email at komal.bhardwaj@cloud.com ? I will connect you with the right team.

**Comment by tammyandlee** [comment]
Found a route to support :)
