### ISSUE TITLE
Deprecation of spec.loadBalancerIP service field

### ISSUE THREAD

**Issue by SSvilen** [netscaler/netscaler-k8s-ingress-controller#636]
The loadBalancerIP field is deprecated and will removed in future version of kubernetes. 
As far as I can tell, currently there is no other way to manually set the LoadBalancer IP in service of type LoadBalancer.
Are there nay plans to add a differnt way to set that IP - annotation, etc..?

**Comment by priyankash-citrix** [comment]
Hi @SSvilen,
If you are using NetScaler Ingress controller to configure your service of type LoadBalancer in NetScaler, you can use `service.citrix.com/frontend-ip` annotation to set LoadBalancer IP.
For more information about the supported annotation by NetScaler Ingress Controller please see https://docs.netscaler.com/en-us/netscaler-k8s-ingress-controller/configure/annotations.html.
