### ISSUE TITLE
Separate IP from IPAM (Range) for each ingress

### ISSUE THREAD

**Issue by ddholger** [netscaler/netscaler-k8s-ingress-controller#653]
**Is your feature request related to a problem? Please describe.**
We need for each ingress separate IP from IPAM (Range) for each ingress similar like LB type behaviour.
This would help us to configure the firewall policies in a much more accurate way.

**Describe the solution you'd like**
We need for each ingress separate IP from IPAM (Range) for each ingress.
The controller then should select an IP from a specified IPAM Range.

**Describe alternatives you've considered**
none

**Additional context**
We had already a chat conversation through the google chat channel "Hansemerkur" with Mayur Mohan Patil. He asked us to raise an enhancement request.

**Comment by subashd** [comment]
This is supported with latest IPAM release. 
Release notes for the same is [here](https://github.com/netscaler/netscaler-helm-charts/releases/tag/ipam-v1.2.0).
