### ISSUE TITLE
Prevent duplicate route entries for overlay network

### ISSUE THREAD

**Issue by lithion2** [netscaler/netscaler-k8s-ingress-controller#661]
**Is your feature request related to a problem? Please describe.**
In rare conditions, nodeWatch will add duplicate routes for the overlay network. I've seen this behaviour when upgrading Tanzu K8S cluster (=removing and adding nodes) and nsic does not always see evicted nodes although it has sufficient permissions. 

**Describe the solution you'd like**
Detect duplicate route entries en delete old routes. 

**Describe alternatives you've considered**
none

**Additional context**
Example 
<img width="1375" alt="afbeelding" src="https://github.com/netscaler/netscaler-k8s-ingress-controller/assets/20997496/8d590c07-368a-4cad-a714-c4652ec08c68">

**Comment by subashd** [comment]
@lithion2 
This issue has been fixed in latest build.
https://github.com/netscaler/netscaler-k8s-ingress-controller/releases/tag/2.2.10
