### ISSUE TITLE
CIC doesn’t update netscaler service group members when new nodes are added to the cluster

### ISSUE THREAD

**Issue by sai-thg** [netscaler/netscaler-k8s-ingress-controller#666]
**Describe the bug**
We are experiencing an issue with the Citrix Ingress Controller (CIC) versions 1.38.27 and 1.39.6 where the controller fails to update the NetScaler service group members  with IP’s and node port of the newly created nodes. Specifically, any pods placed on newly created nodes are not being taken into account by the Citrix controller. For example, if an ingress-nginx pod is scheduled on a newly created node, that node is not added as a service group member of the load balancer.

**To Reproduce**

1. Deploy CIC 1.38.27 on to the capv cluster, deploy[ nginx ingress](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx) with n replicas and verify if service group members on the netscaler are added correctly for the nodes where nginx pods are running. This should work fine without issues.
2. Create new nodes in the cluster.
3. Scale up the existing nginx pods and verify that the new pods are scheduled on the new nodes.
4. Log in to NetScaler and check if the service group members are updated with the IPs/node ports of the newly deployed nodes on which the new nginx pods are placed.

* Version of the NetScaler Ingress Controller: 1.38.27
* Version of the VPX: NS13.1 54.29.nc
* CNI : Cilium
* Cilium IPAM Mode: Cluster Pool 

**Expected behavior**
The Citrix Ingress Controller should update the NetScaler service group with the IP addresses of newly added nodes and ensure that nodes hosting new pods are properly included in the load balancer.

**Additional context**
New nodes are added correctly to the cluster and Citrix logs detect that node addition, and endpoints are being watched as expected. However, nodes go through multiple updates before an address with type `ExternalIP` is added to `status.addresses`.  The CIC relies on a cached Node object to manage IP addresses for the load balancer. when a Node is updated, if it does not have a spec.podCidr (we are using Cilium in cluster-pool IPAM mode, which sets podCidrs on CiliumNodes instead), the CIC's cache does not update with the new ExternalIP in the .status.addresses field. This results in the node not being added to the service group, causing load balancer issues.  

Below is the code (/usr/src/triton/kubernetes/kubernetes.py) that may be  responsible for the above observed behaviour;
```if self.node_watch_for_routes and not ignore_event_for_feature_node_watch:
            nsroute = self.netskaler.nsroutes.get(routename)
            if nsroute:
                if (nodeinfo['Network'] is not None and nodeinfo['Netmask'] is not None and nodeinfo['InternalIP'] is not None):
                    if nsroute.network != nodeinfo['Network'] or nsroute.netmask != nodeinfo['Netmask'] or nsroute.gateway != nodeinfo['InternalIP']:
                        # Update existing route
                        logger.debug(
                            "Unconfiguring route. existing: {network: %s, netmask: %s, gateway: %s} modified: {network: %s, netmask: %s, gateway: %s}",
                            nsroute.network,
                            nsroute.netmask,
                            nsroute.gateway,
                            nodeinfo['Network'],
                            nodeinfo['Netmask'],
                            nodeinfo['InternalIP'])
                        self.update_ingress_with_single_route(nsroute, nodeinfo)
            elif routename in self.kubernetes_nodes and (nodeinfo['Network'] is not None and nodeinfo['Netmask'] is not None and nodeinfo['InternalIP'] is not None):
                logger.debug(
                    "Configuring route: {network: %s, netmask: %s, gateway: %s}",
                    nodeinfo['Network'],
                    nodeinfo['Netmask'],
                    nodeinfo['InternalIP'])
                nsroute = self.kubernetes_nodes.get(routename)
                nsroute.update_route_params(nodeinfo)
                self.configure_ingress_with_single_route(nsroute)```

**Comment by subashd** [comment]
hi @sai-thg 

We have released [NSIC v2.1.4 ](https://github.com/netscaler/netscaler-k8s-ingress-controller/releases/tag/2.1.4)with the fix for this issue.
